INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0000729', 'Abdominal Cramps');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0000737', 'Abdominal Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0003126', 'Anosmia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0003862', 'Arthralgia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0004134', 'Ataxia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0004604', 'Back Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0005858', 'Bloodshot eye');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0005874', 'Blushing');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0005904', 'Body Temperature Changes');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0006625', 'Cachexia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0007758', 'Cerebellar Ataxia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0007859', 'Neck Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0007939', 'Syphilitic chancre');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0008031', 'Chest Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0008035', 'Chest wall pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0009193', 'Pain in the coccyx');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0009269', 'Cold intolerance');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0009806', 'Constipation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0010200', 'Coughing');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0010201', 'Chronic cough');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0011124', 'Decreased Libido');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0011991', 'Diarrhea');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0012833', 'Dizziness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0013132', 'Drooling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0013395', 'Dyspepsia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0013404', 'Dyspnea');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0013421', 'Dystonia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0013428', 'Dysuria');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0013456', 'Earache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0014724', 'Eructation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0015230', 'Exanthema');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0015468', 'Facial Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0015644', 'Muscular fasciculation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0015672', 'Fatigue');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0016199', 'Flank Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0016204', 'Flatulence');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0016382', 'Flushing');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0016512', 'Foot pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0017672', 'Glossalgia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0018520', 'Halitosis');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0018681', 'Headache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0018834', 'Heartburn');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0019079', 'Hemoptysis');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0019209', 'Hepatomegaly');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0019559', 'Hip pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0019825', 'Hoarseness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0020175', 'Hunger');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0023218', 'Leg cramps');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0023222', 'Pain in lower limb');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0023380', 'Lethargy');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0024031', 'Low Back Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0024902', 'Mastodynia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0025587', 'Metatarsalgia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0026821', 'Muscle Cramp');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0026837', 'Muscle Rigidity');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0026838', 'Muscle Spasticity');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0026961', 'Mydriasis');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0027066', 'Myoclonus');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0027424', 'Nasal congestion (finding)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0027497', 'Nausea');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0027498', 'Nausea and vomiting');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0027769', 'Nervousness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0027796', 'Neuralgia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0028081', 'Night sweats');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0028084', 'Nightmares');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0028643', 'Numbness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0030193', 'Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0030201', 'Pain| Postoperative');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0030552', 'Paresis');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0030794', 'Pelvic Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0032617', 'Polyuria');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0032781', 'Posterior rhinorrhea');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0033774', 'Pruritus');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0033775', 'Pruritus Ani');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0033777', 'Pruritus of genital organs');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0034642', 'Rales');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0034886', 'Rectal pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0036396', 'Sciatica');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0036572', 'Seizures');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0037011', 'Shoulder Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0037088', 'Signs and Symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0037317', 'Sleep disturbances');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0037384', 'Snoring');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0037763', 'Spasm');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0039070', 'Syncope');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0039591', 'Pain in testicle');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0040460', 'Toothache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0040822', 'Tremor');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0042256', 'Pruritus of vagina');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0042571', 'Vertigo');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0042963', 'Vomiting');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0043144', 'Wheezing');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0085593', 'Chills');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0085594', 'Fever with chills');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0085624', 'Burning sensation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0085631', 'Agitation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0085632', 'Apathy');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0085635', 'Photopsia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0085636', 'Photophobia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0086132', 'Depressive Symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0086189', 'Drug Withdrawal Symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0087169', 'Withdrawal Symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0149651', 'Clubbing');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0149738', 'neurological pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0149751', 'Penile lesion');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0150055', 'Chronic pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0151315', 'Neck stiffness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0151786', 'Muscle Weakness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0151825', 'Bone pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0151827', 'Eye pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0151828', 'Injection site pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0151830', 'Pain in urethra');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0151908', 'Dry skin');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0152029', 'Congestion of nasal sinus');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0152031', 'Joint swelling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0152149', 'Mittelschmerz');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0152447', 'Urethral discharge');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0155002', 'Sudden visual loss');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0156405', 'Ovulation bleeding');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0158369', 'Swelling of limb');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0159028', 'General symptom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0162298', 'Joint stiffness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0178310', 'signs and symptoms of ill-defined conditions');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0178419', 'muscle cramps in the calf');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0178422', 'Cramp in foot');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0184567', 'Acute onset pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0220870', 'Lightheadedness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0221100', 'Hangover from any Alcohol or Other Drugs substance');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0221150', 'Swallowing painful');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0221161', 'Shallow breathing');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0221170', 'Muscular stiffness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0221232', 'Welts');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0221423', 'Illness (finding)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0221512', 'Stomach ache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0221758', 'Stiff back');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0221776', 'Oral pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0221785', 'Pain in wrist');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231217', 'Multiple symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231218', 'Malaise');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231239', 'Fluctuation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231528', 'Myalgia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231529', 'Tenalgia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231617', 'Catch - Finding of sensory dimension of pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231655', 'Scapulalgia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231749', 'Knee pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231753', 'Knee locking');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231772', 'Burning feet');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231780', 'Heel pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231807', 'Dyspnea on exertion');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231811', 'Suffocated');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0231918', 'Nose symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232119', 'Pulsus trigeminus');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232285', 'Dull chest pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232292', 'Chest tightness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232431', 'Cold sweat');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232462', 'Decrease in appetite');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232471', 'Thirsty');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232487', 'Abdominal discomfort');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232492', 'Upper abdominal pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232495', 'Lower abdominal pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232517', 'Gurgling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232602', 'Retching');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232849', 'Bladder pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0232861', 'Discharge from penis');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0233401', 'Psychiatric symptom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0233488', 'Feeling despair');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0233762', 'Hallucinations| Auditory');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0233763', 'Hallucinations| Visual');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0233766', 'Hallucinations| Gustatory');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0233844', 'Clumsiness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0233973', 'Painful penile erection');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0234229', 'Deep pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0234230', 'Pain| Burning');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0234233', 'Sore to touch');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0234238', 'Ache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0234244', 'Tissue Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0234250', 'Pain| Referred');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0234251', 'Inflammatory pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0234254', 'Radiating pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0234255', 'Night pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0234259', 'Sensitive to smells');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0234369', 'Trembling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0234532', 'convulsed');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235004', 'head pressure');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235031', 'Neurologic Symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235050', 'Tingling of skin');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235108', 'Feeling tense');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235129', 'Feeling strange');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235150', 'Feeling Cold');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235162', 'Difficulty sleeping');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235234', 'Pharyngeal dryness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235239', 'Palpitations - fluttering');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235240', 'Pounding heart');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235267', 'Redness of eye');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235282', 'Roaring in ear');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235283', 'Buzzing in ear');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235290', 'bitter taste');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235299', 'Right upper quadrant pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235309', 'Upset stomach');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235524', 'vein pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235678', 'Vaginal odor');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0235710', 'Chest discomfort');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0236000', 'Jaw pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0236040', 'Pain in calf');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0236075', 'Menopausal symptom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0236078', 'Pain in scrotum');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0236080', 'Vaginal discomfort');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0236082', 'Vaginal pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0236083', 'Burning feeling vagina');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0238637', 'Anal pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0238656', 'Ankle pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0238740', 'severe back pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0238741', 'Upper back pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0238973', 'Pain in cheek');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0238995', 'sharp chest pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239134', 'Productive cough');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239266', 'Pain in elbow');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239272', 'Elbow stiff');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239313', 'exercise induced');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239375', 'Numbness of limbs');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239377', 'Arm Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239431', 'severe eye pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239435', 'EYE TENDERNESS');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239511', 'Numbness of face');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239589', 'Pain in finger');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239596', 'stiff fingers');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239649', 'Numbness of foot');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239667', 'Pain in forearm');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239725', 'genital pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239739', 'Tenderness of gums');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239772', 'GREAT TOE PAIN');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239783', 'Inguinal pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239833', 'Hand pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239836', 'Paresthesia of hand');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0239886', 'Frontal headache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240007', 'Inguinal mass');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240094', 'Joint tenderness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240129', 'Knee stiff');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240141', 'LABIAL PAIN');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240194', 'Blue lips');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240211', 'Lip swelling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240273', 'Tender lymph node');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240327', 'Taste| Metallic');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240382', 'mouth swelling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240557', 'Irritation of nose');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240717', 'Perineal pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240805', 'Prodrome');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240812', 'Prostatic pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240940', 'Scalp pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240941', 'Pruritus of scalp');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0240958', 'sciatic nerve pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241032', 'shin pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241039', 'pain in (l) shoulder');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241040', 'painful rt shoulder');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241042', 'Shoulder stiff');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241044', 'SHOULDER TENDERNESS');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241050', 'sitting pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241057', 'Burning sensation of skin');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241136', 'Pain of skin');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241164', 'Skin tenderness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241165', 'Thick skin');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241229', 'Spleen tender');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241374', 'Thigh pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241381', 'throat burning sensation of');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241426', 'Burning tongue');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241494', 'TRUNK PAIN');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241705', 'Difficulty passing urine');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241727', 'walking pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241745', 'Wound pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241898', 'Generalized fatigue');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0241902', 'Grunting respiration');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0242030', 'pain with eating');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0242429', 'Sore Throat');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0262397', 'Breast tenderness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0262578', 'Cramp in lower leg associated with rest');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0263534', 'Beau''s lines');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0266836', 'Infantile Colic');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0268988', 'Pruritus of penis');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0270541', 'Rebound Insomnia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0270697', 'Post-Lumbar Puncture Headache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0270996', 'Eye swelling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0271188', 'Visual halos (disorder)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0278007', 'Normal bowel habits');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0278008', 'Altered bowel function');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0278107', 'Painful ejaculation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0278139', 'Moderate pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0278141', 'Excruciating pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0278144', 'Dull pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0278145', 'Stabbing pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0278146', 'Shooting pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0278148', 'Throbbing pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0281856', 'Generalized aches and pains');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0282005', 'Swelling of scrotum');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0302539', 'spells (neurological symptom)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0312414', 'Menstrual spotting');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0312416', 'Morning Sickness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0312422', 'Blackout - symptom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0314719', 'Dryness of eye');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0332601', 'Cushingoid facies');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0333243', 'Pitting edema');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0333252', 'Hard edema');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0341742', 'Acute retention of urine');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0344232', 'Blurred vision');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0344375', 'Stomach cramps (finding)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0392156', 'Akathisia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0392171', 'Influenza-like symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0392674', 'Exhaustion');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0392678', 'Swallowing problem');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0392701', 'giddy mood');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0401149', 'Chronic constipation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0422833', 'ENT symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423006', 'Discharge from eye');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423571', 'Abnormal sensation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423572', 'Pins and needles');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423575', 'Altered sensation of skin');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423618', 'Throbbing Headache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423628', 'Painful teething');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423636', 'Cardiac pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423653', 'Type of abdominal pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423669', 'Elbow joint pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423673', 'Pain in spine');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423684', 'Thoracic back pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423693', 'Growing pains');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423729', 'Chest pain on breathing');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0423736', 'Scalding pain on urination');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0424489', 'Chapping of lips');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0425449', 'Gasping for breath');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0425481', 'Sighing respiration');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0425485', 'Whooping respiration');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0426359', 'Urinary symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0426390', 'Bladder spasm');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0426396', 'Urine looks dark');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0426484', 'Throat symptom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0426623', 'Excessive upper gastrointestinal gas');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0426636', 'Urgent desire for stool');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0427008', 'Stiffness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0427086', 'Involuntary Movements');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0427149', 'Gait| Drop Foot');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0438716', 'Chest pressure');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0439053', 'Fatigue - symptom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0439814', 'Prickling sensation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0451632', 'Sore nostril');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0451633', 'Sore lip');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0455270', 'Sharp pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0455770', 'Feeling of loss of feeling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0458109', 'Ovarian pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0458118', 'Total body pain syndrome');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0474496', 'Diarrhea and vomiting| symptom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0475858', 'Generalized pruritus');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0476227', 'pricking of skin');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0476270', 'Cardiovascular symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0476288', 'Digestive symptom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0476289', 'Abdominal wind pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0495682', 'cramp and spasm');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0497406', 'Overweight');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0497481', 'Pain in penis');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0518179', 'Change in voice (finding)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0518214', 'Perceived quality of life');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0520966', 'Abnormal coordination');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0521592', 'Oral hypoesthesia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0521632', 'Irritation of penis');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0521668', 'Primary Thunderclap Headache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0522058', 'Carbohydrate craving');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0522067', 'Liver pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0522179', 'Death anxiety');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0522251', 'Sinus pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0522359', 'Vertigo| Constant');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0522365', 'Severe vertigo');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0541798', 'Early Awakening');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0541828', 'Left sided chest pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0541887', 'discomfort rectal');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0541976', 'gas in stomach');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0542476', 'Forgetful');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0546947', 'Choking sensation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0547030', 'Visual disturbance');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0549248', 'electric shock sensation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0549263', 'opiate withdrawal symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0549297', 'ear swelling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0549299', 'uti symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0549391', 'bladder discomfort');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0553668', 'Labored breathing');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0553713', 'BREAST PAIN FEMALE');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0557875', 'Tired');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0558148', 'Yellow complexion');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0558489', 'Renal pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0558920', 'Lump on thigh');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0558921', 'Rectal symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0559687', 'Congestion of throat');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0560024', 'Swelling of eyelid');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0562483', 'Persistent cough');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0563275', 'Right sided chest pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0563277', 'Right sided abdominal pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0563278', 'Upper chest pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0564820', 'Pain in left arm');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0564821', 'Pain in right arm');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0564822', 'Pain in left leg');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0564823', 'Pain in right leg');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0574002', 'Edema of foot (finding)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0574068', 'Rib pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0575090', 'Equilibration disorder');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0577100', 'Difficulty in ability to defecate');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0577573', 'Mass of body region');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0578046', 'Maxillary sinus pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0578050', 'Pain of lymph node');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0578454', 'Neck swelling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0578687', 'Sore eye');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0581334', 'lump on leg');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0581358', 'Gastric spasm (disorder)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0581394', 'Swollen legs');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0581870', 'Hunger pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0581879', 'Felt faint');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0581880', 'Morning headache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0586407', 'Skin symptom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0587054', 'Numbness of finger');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0596601', 'gastrointestinal gas');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0600142', 'Hot flushes');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0677500', 'Stinging Sensation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0679309', 'physical symptom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0683369', 'Clouded consciousness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0687681', 'Feeling feverish');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0694551', 'Right lower quadrant pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0700153', 'Myotonus (finding)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0700184', 'Throat irritation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0700590', 'Increased sweating');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0701824', 'Staggering gait');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0740396', 'chest burning');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0740418', 'Chronic back pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0740425', 'Altered Taste');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0740903', 'allergic symptom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0741396', 'back pain mid back');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0741426', 'back symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0741548', 'bladder symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0741585', 'BODY ACHE');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0744002', 'finger contraction');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0744318', 'Acid reflux SYMPTOMS');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0744633', 'headache acute');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0744648', 'headache persistent');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0745411', 'irregular bleeding');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0746668', 'muscle pain chronic');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0746674', 'Generalized muscle weakness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0746683', 'MUSCULOSKELETAL Chronic pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0746779', 'nausea chronic');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0747927', 'pregnancy signs');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0748706', 'side pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0750248', 'Chronic vertigo');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0750731', 'Body| Physical Appearance');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0751138', 'Myofacial Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0751144', 'Fasciculation| Benign');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0751295', 'Memory Loss');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0751372', 'Nerve Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0751407', 'Pain| Migratory');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0751409', 'Upper Extremity Paresis');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0751410', 'Lower Extremity Paresis');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0751492', 'Sciatica| Bilateral');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0751495', 'Seizures| Focal');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0751535', 'Syncope| Cardiogenic');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0751559', 'Pulsatile Tinnitus');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0751725', 'Posterior Cervical Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0795691', 'HEART PROBLEM');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0795701', 'Neck cramps');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0812426', 'Kidney problem');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0838224', 'Pain in joint| forearm');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0839476', 'Pain in upper arm');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0839480', 'Pain in limb| lower leg');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0847550', 'red nose');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0847554', 'lump in throat');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848051', 'lumps behind ears');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848168', 'out (of) breath');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848178', 'bad nerves');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848241', 'weight problem');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848259', 'male puberty');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848277', 'room spinning');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848283', 'rundown');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848290', 'sick to stomach');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848332', 'Spots on skin');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848400', 'weight loss problem');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848404', 'weight gain problem');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848464', 'clogged ear');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848633', 'sinus pressure');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848641', 'rash lips');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848720', 'prostate problem');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0848724', 'circulation problem');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849370', 'blemishes');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849668', 'peri-menopausal');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849759', 'charmed');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849791', 'sinus drainage');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849796', 'ear congestion');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849824', 'change (in) bowel movements');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849850', 'blotch');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849852', 'skin bump');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849907', 'Itching of ear');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849911', 'ear popping');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849959', 'feeling dizzy');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849963', 'Feeling nervous');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849967', 'feeling run down');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849970', 'Feeling tired');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0849986', 'foreskin swelling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0850015', 'unwanted hair');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0850045', 'intestinal pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0850149', 'Dry cough');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0850630', 'tingling in fingers');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0850674', 'Twitching eye');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0851121', 'digestive problem');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0853204', 'No Side Effect');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0853946', 'pain aggravated');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0856864', 'Headache fullness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857027', 'Feeling Sick');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857051', 'bad dreams');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857057', 'blotchy');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857072', 'Shaking of hands');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857073', 'cold hands & feet');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857126', 'impending doom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857160', 'leg numbness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857172', 'persistent dry cough');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857177', 'arthritic pains');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857213', 'cramp in lower abdomen');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857233', 'unable to focus');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857245', 'Redness of face');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857248', 'painful feet');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857257', 'bloated feeling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857336', 'burning sensation in face');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0857516', 'floppy');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0858598', 'taste salty');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0858600', 'taste sweet');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0858665', 'stomach burning sensation of');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0858666', 'stomach dull pain of');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0858708', 'itch burning');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0858709', 'pruritus of both hands');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0858722', 'Facial twitching');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0858968', 'redness of legs');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0859371', 'Burning lips (sensation)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0860277', 'sour stomach');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0863079', 'eyes stinging');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0863085', 'sore feet');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0863105', 'sore back');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0872410', 'Posturing');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0877113', 'Painful scar');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0877462', 'tingling mouth');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0877491', 'bumps tongue');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0877495', 'tingling tongue');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0877605', 'burning anal');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0877716', 'Burning sensation of leg');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0877717', 'Burning mouth (sensation)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0917801', 'Sleeplessness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0920154', 'spleen pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0920289', 'Sluggishness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0946092', 'gas/bloating');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0947967', 'coma states');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0948094', 'laziness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0948239', 'vomiting of medication');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0948396', 'Frequent headache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0948521', 'itching mouth');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0948775', 'high weight');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C0949445', 'Cervical Dystonia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1096300', 'genital burning');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1096446', 'slight fever');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1096717', 'pain during injection');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1257861', 'Colonic Inertia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1260880', 'Rhinorrhea');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1274925', 'Skin-ache syndrome');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1282310', 'Intermittent pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1291077', 'Abdominal bloating');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1306878', 'Menopausal discomfort');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1321587', 'Breathing abnormally deep');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1321898', 'Blood in stool');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1377828', 'Paraneoplastic Opsoclonus Ataxia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1384493', 'Catarrh');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1397014', 'Imbalance');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1442877', 'Sore skin');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1443924', 'Severe diarrhea');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1446787', 'Cramping sensation quality');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1517205', 'Flare');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1579838', 'Sore mouth');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1579931', 'Depressed - symptom');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1704205', 'Pharyngeal swelling');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1704276', 'Spasmodic movement');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1705500', 'Flasher - visual manifestation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1718341', 'Soft tissue pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1744601', 'Abnormal heart beat');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C1960719', 'Pain characterized by provoking factor');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2016599', 'pain between shoulder blades');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2032151', 'Pain in bilateral legs');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2032351', 'Pain in left hand');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2032395', 'pelvic pain on the left');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2032420', 'Pain in right hand');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2116289', 'neck Muscle Tension');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2126129', 'constant Tinnitus');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2126231', 'light bleeding between periods (symptom)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2129214', 'Loose stool');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2141922', 'Pain in left hip');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2142181', 'Pain in left knee');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2169806', 'recurrent muscle twitches (symptom)');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2188199', 'Continuing headache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2199592', 'earache of right ear');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2202100', 'Pain in right hip joint');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2202235', 'Pain in right knee');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2203300', 'worse headaches');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2220048', 'Bilateral knee pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2220248', 'severe Earache');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2242996', 'Has tingling sensation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2364111', 'Ageusia');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2364135', 'Actual Discomfort');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2370950', 'Aural pressure');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2830454', 'Other fatigue');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2896456', 'Pain in left thigh');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2945698', 'panic symptoms');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2957106', 'headache severe');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C2985336', 'Urge to Push');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C3179196', 'Myofascial Trigger Point Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C3257803', 'Watery eyes');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C3640009', 'Annoying Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C3640011', 'Miserable Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C3640014', 'Unbearable Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C3640015', 'Hurting Pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C3665346', 'Unspecified visual loss');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C3714552', 'Weakness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C3839047', 'Severe dry skin');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C3853138', 'Very mild pain');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C3900051', 'Amotivation');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C4024610', 'Leg muscle stiffness');
INSERT INTO ontology.symptoms (symptom_id, description) VALUES ('C4042866', 'Symptom Flare Up');