-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 15:45:33 2019
-- Model: hcmdb_model   Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hcmdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hcmdb` ;

-- -----------------------------------------------------
-- Schema hcmdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hcmdb` DEFAULT CHARACTER SET utf8 ;
USE `hcmdb` ;

-- -----------------------------------------------------
-- Table `hcmdb`.`diseases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hcmdb`.`diseases` ;

CREATE TABLE IF NOT EXISTS `hcmdb`.`diseases` (
  `disease_id` INT NOT NULL,
  `disease_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `records_count` INT NULL,
  `has_symptom_count` INT NULL,
  `has_treatment_count` INT NULL,
  PRIMARY KEY (`disease_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hcmdb`.`disease_symptoms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hcmdb`.`disease_symptoms` ;

CREATE TABLE IF NOT EXISTS `hcmdb`.`disease_symptoms` (
  `disease_id` INT NOT NULL,
  `symptom_id` INT NULL,
  `count` INT NULL,
  `rank_score` DECIMAL(10) NULL,
  PRIMARY KEY (`disease_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hcmdb`.`disease_anatomy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hcmdb`.`disease_anatomy` ;

CREATE TABLE IF NOT EXISTS `hcmdb`.`disease_anatomy` (
  `disease_id` INT NOT NULL,
  `anatomy_id` INT NULL,
  PRIMARY KEY (`disease_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hcmdb`.`anatomy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hcmdb`.`anatomy` ;

CREATE TABLE IF NOT EXISTS `hcmdb`.`anatomy` (
  `anatomy_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`anatomy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hcmdb`.`symptoms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hcmdb`.`symptoms` ;

CREATE TABLE IF NOT EXISTS `hcmdb`.`symptoms` (
  `symptom_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`symptom_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hcmdb`.`disease_treatments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hcmdb`.`disease_treatments` ;

CREATE TABLE IF NOT EXISTS `hcmdb`.`disease_treatments` (
  `disease_id` INT NOT NULL,
  `treatment_id` INT NULL,
  `count` INT NULL,
  PRIMARY KEY (`disease_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hcmdb`.`treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hcmdb`.`treatment` ;

CREATE TABLE IF NOT EXISTS `hcmdb`.`treatment` (
  `treatment_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`treatment_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
